name: Ansible Only Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "ansible/**"

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible (fixed version)
        run: pip install ansible==13.0.0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      - name: Get EC2 public IPs
        run: |
          cd ../
          terraform init -input=false
          terraform output -raw ec2_1_public_ip > ./ansible/ec2_1_ip.txt

      - name: Debug EC2 IP
        run: cat ./ansible/ec2_1_ip.txt

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/aws-study.pem
          chmod 600 ~/.ssh/aws-study.pem

      - name: Run Playbook
        run: |
          ec2_1_ip=$(cat ec2_1_ip.txt)
          ansible-playbook \
            -i "$ec2_1_ip," \
            playbook.yml \
            -u ec2-user \
            --private-key ~/.ssh/aws-study.pem \
            --ssh-extra-args='-o StrictHostKeyChecking=no'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"