name: Terraform CI/CD

on:
  pull_request:
    paths:
      - "*.tf"
      - "*.tftest.hcl"
      - ".github/workflows/*.yaml"
      - "ansible/**"
  push:
    branches: [main]
    paths:
      - "*.tf"
      - "*.tftest.hcl"
      - ".github/workflows/*.yaml"
      - "ansible/**"

jobs:
  # Pull Request 用ジョブ (承認不要)
  terraform-plan:
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Test
        run: terraform test

      - name: Terraform Plan
        run: terraform plan

  # Push 用ジョブ (承認必須)
  terraform-apply:
    needs: [terraform-plan]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      - name: Terraform Destroy
        run: terraform destroy

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test

      - name: Terraform Apply
        run: terraform apply -auto-approve